#!/bin/bash
#
# Usage:
#   maint/via-cargo-install-in-ci PACKAGE [CARGO ARGS..]
#
# Installs PACKAGE with `cargo install --locked`.
#
# You should consider whether to specify `--version`:
# without that, you're no longer hermetic;
# instead, you'll pic up upstream updates to that cargo package.
#
# Reuses a previously-built binary if it's found in the cache.
# The directory `cache/` should be cached by .gitlab-ci.yml:
#
#  some-job:
#    script:
#      - maint/via-cargo-install-in-ci cargo-audit
#    cache:
#      paths:
#        - cache

set -euo pipefail

badusage () { echo >&2 "$0: bad usage: $1"; exit 8; }

case "$1" in
    -*) badusage 'first argument must be command (package)' ;;
esac

cache="$*"
cmd="$1"; shift

case "${1-}" in
    [^-]*) badusage 'subsequent arguments must be options to cargo install' ;;
esac

cache="${cache// /,}"
cache="cache/$cache"

if cp -v "$cache" "$CARGO_HOME"/bin/"$cmd"; then exit 0; fi

mkdir -p cache
cargo install --locked "$@" "$cmd"
cp -v "$CARGO_HOME/bin/$cmd" "$cache"
