[package]
name = "tor-config-shared"
version = "0.46.0"
authors = ["The Tor Project, Inc.", "Wesley Aptekar-Cassels <wesleyac@torproject.org>"]
edition = "2024"
rust-version = "1.91"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Configuration information that is shared between arti, arti-relay, and other Arti projects."
keywords = ["tor", "arti"]
categories = ["config"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
experimental = ["opentelemetry"]
opentelemetry = ["dep:opentelemetry_sdk", "dep:opentelemetry-otlp", "__is_experimental"]

__is_experimental = []

[dependencies]
amplify = { version = "4", default-features = false, features = ["derive"] }
derive-deftly = { version = "~1.11.3", features = ["full", "beta"] }
opentelemetry-otlp = { version = "0.32.0", optional = true }
# TODO: Figure out why this feature is needed, and how it interacts with non-tokio runtimes.
opentelemetry_sdk = { version = "0.32.1", features = ["rt-tokio"], optional = true }
serde = { version = "1.0.103", features = ["derive"] }
tor-config = { path = "../tor-config", version = "0.46.0" }
tor-config-path = { path = "../tor-config-path", version = "0.46.0" }

[package.metadata.docs.rs]
all-features = true
