#!/usr/bin/env bash

set -xeuo pipefail

# Tell shellcheck that yes, we know that we're sourcing a file.
# shellcheck disable=SC1091
source tests/chutney/arti.run

# Validate that these are set (from arti.run)
[ -n "${target:?}" ]
[ -n "${chutney_bin:?}" ]

CHUTNEY_START_TIME=300 "${chutney_bin}" bootstrap "$target"
