#!/usr/bin/env python3

# stdlib imports
import os
import sys
import subprocess

# stdlib "from" imports
from pathlib import Path

# local imports
from config import Config

assert __name__ == "__main__"

_SCRIPT_NAME = Path(sys.argv[0]).name
_SCRIPT_DIR = Path(sys.argv[0]).parent.resolve()

config = Config.load_json(Path(_SCRIPT_DIR).joinpath("arti.run.json"))

config.export_env()
os.environ["CHUTNEY_START_TIME"] = "300"

subprocess.run([config.chutney, "init", config.network], check=True)
subprocess.run([config.chutney, "bootstrap"], check=True)
