#!/usr/bin/env bash
set -xeuo pipefail

cd "$(git rev-parse --show-toplevel)"

# Tell shellcheck that yes, we know that we're sourcing a file.
# shellcheck disable=SC1091
source tests/chutney/arti.run

# Validate that these are set (from arti.run)
[ -n "${target:?}" ]
[ -n "${chutney_bin:?}" ]

"${chutney_bin}" stop
