#!/bin/sh
#
# This hook was set by cargo-husky v1.5.0: https://github.com/rhysd/cargo-husky#readme
#

set -e

echo '+cargo fmt --all -- --check'
cargo fmt --all -- --check

echo '+cargo clippy --all-features --all-targets -- -D warnings'
cargo clippy --all-features --all-targets -- -D warnings

echo '+cargo test --all'
cargo test --all

