[package]
name = "test-temp-dir"
version = "0.5.0"
# TODO make this 1.x.  Let's say, do this in December 2024 or January 2025
authors = ["The Tor Project, Inc.", "Ian Jackson <iwj@torproject.org>"]
edition = "2024"
rust-version = "1.86"
license = "MIT OR Apache-2.0"
homepage = "https://gitlab.torproject.org/tpo/core/arti/-/wikis/home"
description = "Temporary directories for use in tests"
keywords = ["testing", "fs", "filesystem", "temporary", "temp"]
categories = ["development-tools::testing"]
repository = "https://gitlab.torproject.org/tpo/core/arti.git/"

[features]
default = []
full = []

[dependencies]
anyhow = "1.0.23"
derive_more = { version = "2.0.1", features = ["full"] }
educe = "0.4.22"
tempfile = "3"
