#!/usr/bin/env bash
#
# List the current version of every crate.

set -euo pipefail

TOP=$(dirname "$0")/..

for crate in $("${TOP}/maint/list_crates") ; do
    printf "%-16s " "$crate:"
    grep ^version "$TOP/crates/$crate/Cargo.toml" | \
	head -1 | \
	sed 's/^version *= *//' |\
	tr -d '"'
done
