#!/bin/sh
#
# Downgrades every one of our dependencies in Cargo.lock to the
# earliest version listed in our Cargo.toml files.  (And then
# re-upgrades a few second-order dependencies that aren't actually
# supported by our first-order dependencies in their oldest versions.)

cargo +nightly update -Z minimal-versions
cargo update \
      -p crc32fast \
      -p zeroize_derive:1.1.1 \
      -p env_logger:0.5.0 \
      -p synstructure:0.12.0 \
      -p nix:0.4.2
