#!/usr/bin/env bash

if git grep -rnI "^#\!/" :/ | grep -v "#\!/usr/bin/env"
then
	echo "Absolute shebangs found, replace them with \"#!/usr/bin/env\""
	exit 1
else
	echo "Everything seems ok"
	exit 0
fi
