#!/usr/bin/env bash

set -euo pipefail

cache_dir=cache/"$CI_JOB_IMAGE"

mkdir -p "$cache_dir"

for cmd in "$@"; do
    cache="$cache_dir/$cmd"

    if cp "$cache" "$CARGO_HOME"/bin/; then continue; fi

    cargo install --locked "$cmd"
    cp -v "$CARGO_HOME/bin/$cmd" "$cache"
done
