/* type=fallback */
/* version=4.0.0 */
/* timestamp=20210412000000 */
/* source=offer-list */
//
// Generated on: Thu, 21 Oct 2021 13:07:39 +0000

vec![
    // Nickname: Assange008fr
    fallback(
        "ADB98B27D7A3FB5732068FD23602A1BCB3BE9F38",
        "qvCRVASsfT9VoZ/igQFqnekhgr1LUQxN9ijWGKXQ06Q",
        &[
            "62.210.105.46:9001"
        ],
    ),
    // Nickname: AquaRayTerminus
    fallback(
        "616081EC829593AF4232550DE6FFAA1D75B37A90",
        "7gZmP2wRc+j0T+HrF0HocfALwdcoDcULP0Fa/P31I5s",
        &[
            "95.128.43.164:443",
            "[2a02:ec0:209:10::4]:443"
        ],
    ),
    // Nickname: beerbox
    fallback(
        "D079D6818926684C5979C18171FB18862A4A5792",
        "rdXXiaF5xMfwqN/DAku/4xLnD76R/GpX1jVqoj9BwE4",
        &[
            "5.79.79.133:443"
        ],
    ),
    // Nickname: NoSuchRelay
    fallback(
        "CA53F344DB85248D69A97E900A0EC3C31AC04D25",
        "0km6CJmtkjFFaTz6UIuzlxo2s+lumKdhuyDVy7zOjlI",
        &[
            "91.121.103.117:9001"
        ],
    ),
    // Nickname: rucola
    fallback(
        "C8AE26D4819504D0157AD4C5DE7D5A0A7E190D10",
        "o0ex8Qhak8+ZtrhWuPpDavXlNkM3hbreEU24y8P4FzQ",
        &[
            "109.70.100.9:443",
            "[2a03:e600:100::9]:443"
        ],
    ),
    // Nickname: albator
    fallback(
        "E05CAC929E391787077066C29461A9D22ECF0809",
        "+BlXEji392MtoNoNRH9FOPm+Ofzd//0Gry8Xa2TRpA8",
        &[
            "83.205.231.204:9001"
        ],
    ),
    // Nickname: rinderwahnRelay7L
    fallback(
        "EE4AF632058F0734C1426B1AD689F47445CA2056",
        "7jdssCmDIpvk9P8vPfMuTKYAnrtGoMacTEvA23H0vnE",
        &[
            "37.252.187.111:443",
            "[2a00:63c1:c:111::2]:443"
        ],
    ),
    // Nickname: iriseden
    fallback(
        "00C22D3BC1822EB8EA380AF04245337399E796E2",
        "5MXSGF4/sDDRGJFjkXdGT8xktaoSfWrMK5Pn+ThiCF0",
        &[
            "144.76.157.242:9001",
            "[2a01:4f8:200:30f5::103]:9001"
        ],
    ),
    // Nickname: netimanmu
    fallback(
        "B4CAFD9CBFB34EC5DAAC146920DC7DFAFE91EA20",
        "NUnPZauZMGtJ2Ytt3J5/VykSsmfAvFrWQY78JzVGX4g",
        &[
            "212.47.233.86:9001",
            "[2001:bc8:630:194::1]:9001"
        ],
    ),
    // Nickname: StriveForFreedom
    fallback(
        "55403B9653A81F68C39787E000BD9F97E1F3B250",
        "18GBS0vZ8jRTGUkLFW/ZsAP2BCtpm1IW2/uHbvyAFUw",
        &[
            "173.212.231.228:9001"
        ],
    ),
    // Nickname: guidemenow
    fallback(
        "16824F885D72B4FA7A5090E08D877E5404BC214D",
        "eQVZPQxRhs2/HxS1epGjER9pDujxaRnNURZX+c67cus",
        &[
            "62.216.54.29:9001"
        ],
    ),
    // Nickname: summalummadooma
    fallback(
        "4E98AA295B7171996D18DD1F6A19F64AB4036B4A",
        "6Ou2ADIB7a7O3nwVCK1pGXOXS8M0XFq7w9U5mnICn3M",
        &[
            "213.239.213.190:443"
        ],
    ),
    // Nickname: vahShei7Eeth
    fallback(
        "6C1A8CBE589906EEC6E73F4F286AC29AF7521E1D",
        "qgyf68eOnJwJF/5Q+sTDrukzBxfVBxbN58DlWDj2FqA",
        &[
            "5.9.37.162:9001",
            "[2a01:4f8:161:21a9::2]:9001"
        ],
    ),
    // Nickname: DeLoreanDynamite
    fallback(
        "43E896D36AAB20B5B63094BBC52CAD4B560E47BF",
        "Thdd8Dy3WKFpoDcbeWMfjX7fHZ+DaigzinsrSVFpI60",
        &[
            "82.69.47.114:443"
        ],
    ),
    // Nickname: Casper10
    fallback(
        "ECD239A3B2CAD7375D218B624BCA270CDBFE2A29",
        "rfCqkdMzdbf8hRpAJYjN1gyjKQm0rLiRsge5rY2hDNE",
        &[
            "51.15.177.140:993",
            "[2001:bc8:3fec:500:7ea::]:993"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "051FB296CDF787B5B97A9F2C5CD6FA3E10C27045",
        "dm7EPtIhiQRhqX955zMJ9c6HfqW5AuInEAslNJHBN1M",
        &[
            "209.141.57.122:443"
        ],
    ),
    // Nickname: jaures2
    fallback(
        "F24F8BEA2779A79111F33F6832B062BED306B9CB",
        "v6YjNsq1tLsAUt+FlU2uv0Bpkn4iJ9UmkhYAcS3aBJk",
        &[
            "193.234.15.58:443",
            "[2a00:1c20:4089:1234:cdae:1b3e:cc38:3d45]:443"
        ],
    ),
    // Nickname: CryptoHouse
    fallback(
        "91BAB54C6923454F4E5EDC59313C45002B238665",
        "5b/byK1J9ajhhx/Sng1aa9qvRQlkm+iFqUeSy/LyV/s",
        &[
            "185.228.138.252:8080",
            "[2a03:4000:23:409:748d:52ff:fe41:cdcc]:8080"
        ],
    ),
    // Nickname: Shredder
    fallback(
        "5887DD4FC027A14DE4985429C38BF78C297B7795",
        "xKZHjZu1u/rbdKQ3zQFpY3bh81nkj1prmXoof1sRX2U",
        &[
            "77.23.45.123:9001"
        ],
    ),
    // Nickname: arnall
    fallback(
        "A1B7C1F83E5DA4376FD2E1DBA7AC28A71AB332AD",
        "J0mSrDHAZDyxnYTwNDWs8cGEiBug/JR0glGzwc0hXS8",
        &[
            "82.103.140.87:443"
        ],
    ),
    // Nickname: DTFNODE64
    fallback(
        "A28D6C0BAA9EEBD288713357C46CF6EF081EF673",
        "ZqFNbbaEwDOeo1JGFZpVidCFtGAQsl3W5X1eCJJUn5g",
        &[
            "37.221.66.248:443",
            "[2001:678:6d4:6020::4dea:105]:443"
        ],
    ),
    // Nickname: spargel
    fallback(
        "530277866466A1425F43A73DBFCB5FC7410C9852",
        "LYX9yI5sG8+0aJf8odum0TVPkyYdaKeeC1vBcN2SMIQ",
        &[
            "109.70.100.1:443",
            "[2a03:e600:100::1]:443"
        ],
    ),
    // Nickname: s0menickname
    fallback(
        "34FA04EFC21C4B8461FCE82E908FDD53DF1E7962",
        "ypxWz/v5DtGMAOQx6u8AFNkyn5Kfa8pxSbQWA0x9aWQ",
        &[
            "185.82.127.141:9001"
        ],
    ),
    // Nickname: myTorRelay2
    fallback(
        "1FCA426BBD7EDCC6C0FFF013D0FD9531B16A5845",
        "axeXL7y3isp39ksCGzGmYj0/MHOrhH0Dmjv6M6CEhNE",
        &[
            "45.76.218.50:9001"
        ],
    ),
    // Nickname: Chenjesu
    fallback(
        "5DB9AE27A44EB7B476CC04A66C67A71C97A001E6",
        "knBe0GKhDCZFO3TVfuopHQhtfd7aJbXBE2heIa2RjvQ",
        &[
            "54.36.205.38:9001"
        ],
    ),
    // Nickname: funkturm
    fallback(
        "130E69E8F783DEF256E757FA78154B7DC2A39E0E",
        "Q3wPep7BLmLxIcGFg0Uijsm2j4rLTClX8pdomYsm9+U",
        &[
            "185.72.247.145:9001"
        ],
    ),
    // Nickname: INSRelay38at5443
    fallback(
        "23D5D8219A8EB7610AB33CFAD589FD72A844356A",
        "AlNfLyt8WoXVJRcUTMRReEedezbyqQ6/4/pyCsjfdOc",
        &[
            "140.78.100.38:5443"
        ],
    ),
    // Nickname: tconionrelay
    fallback(
        "023EBBC57BEB7F45473B3DC2AA811FB3AABA4466",
        "z/4MClWR+WKaDcqZFYE3KW2zkPWzsGtYCssdq+uv/Ag",
        &[
            "173.75.39.61:9001"
        ],
    ),
    // Nickname: Grexit
    fallback(
        "A0056E0F3773DD99C1ED298B956A2ACEE1BFB5FD",
        "P8/UeCYjPSS7ImQD3XSZx4LQJnnugVt4F3tmuOSA8NE",
        &[
            "185.4.132.135:443"
        ],
    ),
    // Nickname: Daenerys
    fallback(
        "E312A938D71045BE3A5C1FF3AB87CF7464194861",
        "3vNxh81kHa+lpqQs3H8teh/XLxQMQCXip0sg7bpNvIw",
        &[
            "104.244.77.250:443",
            "[2605:6400:30:faa9:4abe:8b09:7ef9:18e6]:443"
        ],
    ),
    // Nickname: Pickachu
    fallback(
        "34F2DBF5595FF8323665BEC7DD8D2D28F9697B2C",
        "AljHoVkGCnf0qZVHn4814eQuABXo5Q1QDoR4cC0maeY",
        &[
            "45.67.229.37:9001"
        ],
    ),
    // Nickname: dolemite
    fallback(
        "438F3EA4C9FB0DB63F5377A3271AB5435FAD7E04",
        "mL3ZgqOEjbLGw3mh/NP59W0qj1wQJ0T/P2SJLg49+j4",
        &[
            "193.108.117.103:9001"
        ],
    ),
    // Nickname: KagamineLenWoRd
    fallback(
        "B1A0F1143789466AADD5FAE5948C8138548EECEC",
        "SZK0bMP6XHQdOHgLMLireGD/+mlIuMXHRGjkdOhjGcw",
        &[
            "158.101.138.180:443",
            "[2603:c021:8000:d00::c1]:443"
        ],
    ),
    // Nickname: PCGGRelay
    fallback(
        "1619F4FCE1C5324CAB703EAD94285B1ABE39F912",
        "TnNGKFyZZ5fQLPjKumen4fnPZjGMcoC5Prdn61ZsR6E",
        &[
            "110.141.223.194:9001"
        ],
    ),
    // Nickname: Phoenix
    fallback(
        "270EECB837AD914C01ACC777152AEEB1EBCDBDE5",
        "2T82j2V9O9h9iNTyT1ySCHplBP8nJJNw/RT3mP+ejxY",
        &[
            "104.149.139.42:8080"
        ],
    ),
    // Nickname: Starlight
    fallback(
        "0D8877392F2FF5AD8D8E5BC438087F02EF97B904",
        "GHRvTLnPdOb9GjZFOhs+RruNj+gRTf0XGwg6YY0wA58",
        &[
            "58.107.88.237:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "B1AE47B97B6952B3B8B2CD19B57183CF5C801348",
        "sIyfnvTscaMyOcm6JWBIXX04yBK/1YdTpsXohl7kPKQ",
        &[
            "198.245.61.171:443"
        ],
    ),
    // Nickname: jaalkabil
    fallback(
        "CB5700E1FB46FC98251DD8F0852B63A3B78DB830",
        "2mkYj1buhCF2Io2Gn6oVWlLB9SZUGSTtlbXWFPtmtwA",
        &[
            "198.211.40.226:9001"
        ],
    ),
    // Nickname: normaray
    fallback(
        "CD39C258265B25EAA4ABA4FDCB2DF98104CAA362",
        "Hzx0yV+7XP+7Q/MBjwmXnOeP6cabzxOJ5wTvF64uRCU",
        &[
            "94.130.200.167:443"
        ],
    ),
    // Nickname: mullbinde5
    fallback(
        "675CFAC38BE3C9A26C3A2DD7CBC0E616F68624CA",
        "O+XHsVlKlFtpRI6/MH6E96Glg8zCxTwd8zrMflOZDWo",
        &[
            "136.243.60.188:9001",
            "[2a01:4f8:212:1b8b:3::8]:9001"
        ],
    ),
    // Nickname: fs0ciety
    fallback(
        "BC5F00B573D277C4BFA8F0FBAA47E074D0994C1C",
        "ykQwspuzy4Z4DnaIz5X+W3FXcx7njaQJDDurWjr9tXw",
        &[
            "81.28.206.216:9001"
        ],
    ),
    // Nickname: roTor
    fallback(
        "867982ADCFBE55EC1C00A5B34C8991FF87605906",
        "oueol0omKaSO/m+5zw9X0c4tIM90NL5ZZpifzosRuRc",
        &[
            "78.198.147.227:9001"
        ],
    ),
    // Nickname: MarinAsagi
    fallback(
        "F98A70E5427BFF111640011F7AE31E537ECF1DD2",
        "OcaXdW4jmkLubdzZ3NK7o9c7ObrfCwN8YDec6V0Khzw",
        &[
            "23.239.113.101:443"
        ],
    ),
    // Nickname: OhYee
    fallback(
        "0A5476625BAC0573A82FCB432ACED70E1ED83E93",
        "0+gl2NM0OeUOQQR+byKjFHNZRqvYrIyvujvac9Lzi0Y",
        &[
            "173.212.219.49:6666",
            "[2a02:c207:2047:1305::1]:6666"
        ],
    ),
    // Nickname: BarryBen
    fallback(
        "87AA1BE4A39529DD86194738DFB59DC698F3136B",
        "ZLRBIIEdG5KpfHEPYFTsd59ad+Bat89sq/kXItUThcs",
        &[
            "52.205.15.239:9001"
        ],
    ),
    // Nickname: ALiteralBird
    fallback(
        "262B0B749C9088446A5521C4E98173DED815FD5A",
        "Dmhh6c/wxsbyxuJKTH2RAt+GEmUhqYwaKbPuI4k41r0",
        &[
            "68.71.27.78:9001"
        ],
    ),
    // Nickname: Piratenpartei10
    fallback(
        "166850D169CC7956E77525A1A9228BC4563CFC8B",
        "lDi/wwZLZnidpId+Y79LcFnSgnAPEbzV80KhZawF1l4",
        &[
            "185.162.251.135:9001",
            "[2a03:4000:1a:5c5:38dc:87ff:fe07:85fb]:9001"
        ],
    ),
    // Nickname: SoySauceR
    fallback(
        "42A51FFF7AB2A2F396CB924B56676F09BCB52245",
        "42TI2YPGn3EaYTeR5p6MGIFJ+5ggXqZ0mr5wey/dFlQ",
        &[
            "157.90.38.9:443"
        ],
    ),
    // Nickname: JanKuciak
    fallback(
        "9C1559C46AD0279EEF6FD187E1B27D939C303086",
        "GKvUbY9Z9kDQ5jly7QCckRZ5zXhzeBiSjRyfPDsKfGQ",
        &[
            "217.79.178.53:444",
            "[2001:4ba0:cafe:5bf::1]:444"
        ],
    ),
    // Nickname: justarandomrelay
    fallback(
        "CC2DD888299ED7B7CA7D7B930352A074EBE1E906",
        "klHUHTLmcDSWhMYEuk0rz2DB5qNMNUaYJBtFKMl0g1o",
        &[
            "195.154.112.228:9001"
        ],
    ),
    // Nickname: ForPrivacyNET
    fallback(
        "1AAC19D892F84910AB94C45092241ABA3CFC4C89",
        "Lrxa+LZeubfwM7njH+WxejwpBSb3jBmm5r9ZERgSYX8",
        &[
            "91.194.84.89:8443",
            "[2001:4ba0:ffff:1ce::2]:8443"
        ],
    ),
    // Nickname: Aurora
    fallback(
        "B9A8969537739F89CBB02E2A91CECFE154B276C7",
        "+ZgZ1GRNFHF+NsqyfvNdiVojzuu39Sa5sw6hCJNH6o0",
        &[
            "159.196.69.117:9001"
        ],
    ),
    // Nickname: cvbnet1
    fallback(
        "20974D28EB668E689D4256046E0E32034375A0A2",
        "MgG9k+OdGHmqt9hrkyKy5Lka6wBX6flv4wq1nHsqPnU",
        &[
            "46.38.236.250:9001",
            "[2a03:4000:2:ba4:88e9:eff:fe89:3637]:9001"
        ],
    ),
    // Nickname: HogTheHedges
    fallback(
        "D0F40C637C5F93D823AAC497007FD07A2F0FABB5",
        "/eI9U1NgQH5MlyZqX9GnINt8XjJ2RQg+FeHSTm22HiU",
        &[
            "209.141.39.200:443",
            "[2605:6400:20:21de::1]:443"
        ],
    ),
    // Nickname: jakfrancjamoze
    fallback(
        "5558F546D2A996DD2F4B6A62A218DF23848452E3",
        "PUPDtHw+a80RvsPcjWaOqNXgmG2q0mZ3Z9CJVSTH9oQ",
        &[
            "5.135.156.12:4899"
        ],
    ),
    // Nickname: 2Contribute
    fallback(
        "A98ADD972045D3CCAEE65C788C3F175BAEA3E324",
        "yuMySaMmsRbD20OnF/2L6XNckD9NIbpbvOmBv03UQ38",
        &[
            "83.161.151.178:9001"
        ],
    ),
    // Nickname: tor1VaxariNet
    fallback(
        "BCC93B0ACA325374086A5100D02843A04EBDCC00",
        "kf8qZ71bjTjWOJ8fAl/Thn01itC6SaOjVC0gCvSMkyw",
        &[
            "85.214.141.24:9001",
            "[2a01:238:420e:ae00:1c37:63c1:24c0:ff75]:9001"
        ],
    ),
    // Nickname: UnvisitedNativity
    fallback(
        "58B44B5591A96EC08114B041CC6B1BB1521DF2BE",
        "m0J6jPgNJrSYFU5Y2b0O4kbss67fWxGgso9Ha5LAllU",
        &[
            "199.195.250.77:443",
            "[2605:6400:10:549::1]:443"
        ],
    ),
    // Nickname: artikel10buc01
    fallback(
        "ABD9D46C3C026CF6B88574A0707D0BF75A067999",
        "h50PCDAFosOCFxmrzfJn4wedcbcY/yIzU+FTAHa4K9k",
        &[
            "185.100.87.250:8443",
            "[2a06:1700:0:12::1]:8443"
        ],
    ),
    // Nickname: marcuse1
    fallback(
        "EFAE44728264982224445E96214C15F9075DEE1D",
        "s2w6QLaOQFL2tLQoHSS7+hrk42W8RmTK1Q4mp7uasn8",
        &[
            "178.20.55.16:443"
        ],
    ),
    // Nickname: lecirque
    fallback(
        "1BBD716B4973D96E570D334A5776978BFF7E0E5D",
        "W9pgpLxIjub+UUUxGLOJta8hoT+zbjYA4J1HhlgCONc",
        &[
            "151.237.185.134:9001"
        ],
    ),
    // Nickname: Chani
    fallback(
        "3C7F402F5C62A96C7E0DCD5CC850AADF88393802",
        "O2aQkSlkqrXTbBXOGXUNvgZ3jknMFq6Big2IOlKIYvA",
        &[
            "213.164.218.224:443"
        ],
    ),
    // Nickname: Hydra24
    fallback(
        "8F293A6484A0973167B15C4997AB9F24C21143FE",
        "Ti0+25l4V9Yf8Q/+S5ESgji53Ink3IUj9oQo/pYwwkc",
        &[
            "51.83.131.42:9001"
        ],
    ),
    // Nickname: BestofbestBackup
    fallback(
        "26C15ED5282382A843D0774F5170BCCCCCC46D63",
        "ghHyhej2hz5ZakjVQEJpUsux5xl5qJeDPpAxge89dlI",
        &[
            "172.105.89.143:9007",
            "[2a01:7e01::f03c:92ff:fe7c:85f7]:9007"
        ],
    ),
    // Nickname: Fangio
    fallback(
        "65E40F7EDD28E2CF28684E30E0BAB7706819CFC3",
        "cgXu5tvmgUshrJMYDYMMegUKA23ICVMhdaGXQqbS6lg",
        &[
            "179.43.169.20:443"
        ],
    ),
    // Nickname: metM0r
    fallback(
        "C8705CB63A3D3060A649D9FA0514E7E60A1E1A2B",
        "aoHgLkZUwayOrx6wRwBusiMMRNsXB0YcVKPj2dw9yzQ",
        &[
            "174.89.83.82:9001"
        ],
    ),
    // Nickname: jsRelay
    fallback(
        "6111C6005AB56498BE5E35666B2522CEBE17D14E",
        "KptIBxiBe6HmC2rA2w9nD1ChLrvTfwvQ2ut3FL6Y18A",
        &[
            "68.160.242.214:9001"
        ],
    ),
    // Nickname: slacknet
    fallback(
        "6B88E20FEE8EB47F1A8E30207F327005C61A013D",
        "eCRzU3jd6j7YjxbPBzdyh+15zOCwxKPZzYzDX+TEMG4",
        &[
            "144.76.216.252:9001",
            "[2a01:4f8:200:8261::b0]:9001"
        ],
    ),
    // Nickname: alxu2
    fallback(
        "A66E5782FE6097D2824044466776FE912AEFD85B",
        "g5FqIyNBFJiytVI+iHqQ78t1bplZW4LA3KD9ZX9gGlk",
        &[
            "209.141.54.168:443",
            "[2605:6400:20:274::1]:443"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "82CE42D04B5BA616E611E4758861C864B2ACFCA8",
        "mgToQDEVO81J95OlkfA/BPDWwy1qJU6gdkH1f9UD4rU",
        &[
            "107.189.31.241:9100",
            "[2605:6400:30:f02a:faff:1d57:32b7:157f]:9100"
        ],
    ),
    // Nickname: Damnation
    fallback(
        "803FB98BA0FE1709C087E9138CC6096F22083CA5",
        "TRJXzx+zY4VOkRydmZR9vuI//0ywyhUrdNhuNR4qKZs",
        &[
            "123.255.62.137:9001"
        ],
    ),
    // Nickname: arcanum
    fallback(
        "605EE4375EE4C38215C8949F5808863749FD4F4A",
        "dlQkgqs3OdimwEEZsU2OvF0YDCejH82nhdaiuN+STWQ",
        &[
            "5.56.221.113:4020"
        ],
    ),
    // Nickname: BringMeToLife
    fallback(
        "343EC037D633150AFFCC8471E805AABAE1B1D871",
        "PkRKNPUoh5lHEz0kRneBG/Yjd01ExgigzN4i81Y5kTw",
        &[
            "24.151.37.55:42069"
        ],
    ),
    // Nickname: daytoner
    fallback(
        "66B06D59BDFC90EBC6EDE79C558275F2CD4799B0",
        "nTXpqOyiU6okTF8i0ZNjNZuBZgvlEd1fjgOvV/7LT8I",
        &[
            "212.74.233.22:9011"
        ],
    ),
    // Nickname: krigernes
    fallback(
        "03DC081E4409631006EFCD3AF13AFAAF2B553FFC",
        "dq0x/RbnQlMmW6+m67SVo+0cdTuzwVvBYHz70ufSqS4",
        &[
            "185.32.221.201:443"
        ],
    ),
    // Nickname: Quintex77
    fallback(
        "1BBCAEB763CA46DEB565A7251FAA6AC79A388ADD",
        "BsDzql/idGSFuTL8711HWGhcFNFuDIYX+4kGjpdv0xg",
        &[
            "199.249.230.166:443",
            "[2620:7:6001::166]:80"
        ],
    ),
    // Nickname: Lux4
    fallback(
        "C8AAADD3FD1470E7D60D8BC4500F95825F35057D",
        "owqNdWKWiNXu8F1CcEEBJjeT7ZPGGor9BItyyOyDN+Y",
        &[
            "92.38.163.65:9001",
            "[2a03:90c0:83:2908::169]:443"
        ],
    ),
    // Nickname: 8af34cb1
    fallback(
        "C9D02B1644BD47C136E379FDFAF4973D1A1CE07C",
        "3nUtfokJRit8RweJJNIZt0JKDEexw0CFnksuZ0DAQX0",
        &[
            "193.111.26.37:443"
        ],
    ),
    // Nickname: plithismos
    fallback(
        "45047C78E1F5E7B775B0A42F118D4ED64504D09E",
        "bDH2bqx5CVEQxYb3N6SL7OebkcLnm2eygXE7sMDjNwU",
        &[
            "132.226.162.148:9001",
            "[2603:c021:c003:3511:1::]:9001"
        ],
    ),
    // Nickname: Digitalcourage4ip3b
    fallback(
        "35B503FB546815CC9EDE91022555B5D0ED04E389",
        "/mKYwPxEYiC0wFBjtPfCpNA+0NhYc8pJ5O86SH7wmhA",
        &[
            "185.220.102.250:993",
            "[2a0b:f4c1:2::250]:993"
        ],
    ),
    // Nickname: MyCoolNick
    fallback(
        "5EF0AAAEEE7B1282DA0DBAB94669B73E39DD51B6",
        "FR2s/zzL38lqYu6jdObAFO67LRp7RC3C2+JTw03rqWA",
        &[
            "95.216.145.127:9001"
        ],
    ),
    // Nickname: BurnerMeetsTOR
    fallback(
        "1388AB40396F57ED95BB6036E6504CE8E0F622B8",
        "Q/Jn1dHD355ymcP6ZDBhTlSPp/SBaPObCIYrBc+QJd8",
        &[
            "84.160.69.190:9001"
        ],
    ),
    // Nickname: MoldEraTor
    fallback(
        "7332A06B00D6AF54AA804F03C624DFBBC9E66172",
        "sMwKMpHEKTtQvxL9pNqpHDkvhsBdDZ76CiOENchaQ6g",
        &[
            "178.17.173.26:9001",
            "[2a00:1dc0:2451:10::3]:9001"
        ],
    ),
    // Nickname: margate
    fallback(
        "C8A8423DDB3C7E62D0F2A7A88B09BA68710B6AF2",
        "hpfIpSKe1MRPvRvfdjlMQPeDIhmvYDwE5jTcy3KRjxk",
        &[
            "172.222.102.43:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "D30734EC319A37E15155F6B710E9CC8F987FC772",
        "wr9SrKQ96f7kI4qP0B0MWgOaQ1r75/HPtXbalHxF8wA",
        &[
            "5.45.104.171:22",
            "[2a03:4000:6:1547:92dc:911c:7899:e0f2]:22"
        ],
    ),
    // Nickname: Piratenpartei12
    fallback(
        "A7317673B923B591066204FFD299AB2C4150B6BE",
        "MPDV5HxTYeDpYcEgTuho+aAfAqTbo37a3frDNLT/N4w",
        &[
            "37.120.184.36:9001",
            "[2a03:4000:f:512:8475:54ff:fefe:912d]:9001"
        ],
    ),
    // Nickname: c0rexxxkratos
    fallback(
        "8D3BF2751B2C7857839B2E597EB9E092FB583506",
        "08I1CKk9QoagzhYI9EepAE6zih5O1c7H3gEYx5ahzYM",
        &[
            "173.208.141.58:8443",
            "[2604:4300:a:5b:bad:babe:ca11:911]:8443"
        ],
    ),
    // Nickname: a2704f1ae50d753145e
    fallback(
        "6009023303F6881419F4CEDFC4B7FF8FFDF2E3C3",
        "EH2mmFQWY7BbysrFTOr0QawIOf6V7TKBLLU+BTkKGbw",
        &[
            "62.65.40.250:443"
        ],
    ),
    // Nickname: Planetclaire64
    fallback(
        "FA85FE81093FE5D53DDCEA2DBA286E8CCC9C6DDD",
        "+lz3wMMmyVt7b+QGfW975DIe+x3V/moi2XeIs9ny4LQ",
        &[
            "91.143.85.52:465",
            "[2a02:180:6:1::2efe]:465"
        ],
    ),
    // Nickname: OONITestHelper
    fallback(
        "14D2FDC6ABDCD1A27CA32D13AA2C68566D1E8223",
        "ZYdv7pz1i55r3DpC2CPAnGiW7jvHkbWvdJwuVMOX1XY",
        &[
            "37.218.241.28:9001"
        ],
    ),
    // Nickname: AsiaArgento
    fallback(
        "E459E02374D0385D2E2515CBBE707EA208966BCF",
        "8XHMJFV8x8p8QCIHq4V5LDFfguYrZukA0PxPOfHfWN4",
        &[
            "163.172.94.119:9001",
            "[2001:bc8:208a::1]:9050"
        ],
    ),
    // Nickname: Hack2G2
    fallback(
        "87D28EE0C993B250EF93DBE4D2CB0E30244D757C",
        "QF2N/oFl4c5GkHzKIE0OV61RonTA3DhdJzskG39Be2k",
        &[
            "91.121.82.132:9001"
        ],
    ),
    // Nickname: Alastor
    fallback(
        "2EB3C230180694A1E848001E20F36F76A2287039",
        "r0Iw5c4GlYu/um4mwPaKFDVWSO1yQyM/daff7yzKgAY",
        &[
            "62.210.123.24:443",
            "[2001:bc8:30c6:100::dead]:443"
        ],
    ),
    // Nickname: TORRelayCAN
    fallback(
        "B5B666F5F7E910DFF44AD58CD62A4B3F415ECB60",
        "7EK1YWp7W4vGW7IBeJLp55ZKRhjINQb9YLDosL8MMzQ",
        &[
            "192.222.169.71:9001"
        ],
    ),
    // Nickname: waveguide01
    fallback(
        "E7A3DA42BCA86430F089DD32C3FDA33534E76F19",
        "vwpa94lTCBKeb3SHckGotxHLvhkKbcTMCM76/amNyNM",
        &[
            "95.217.30.201:443",
            "[2a01:4f9:c01f:30::1]:443"
        ],
    ),
    // Nickname: tirz
    fallback(
        "32364BEF873944BE481E8BCC7FAE9297F5F39781",
        "69kkkeOZVOJgl7TAFMi/hr0fCqLSDfV20oDPKOLja38",
        &[
            "51.159.144.243:443"
        ],
    ),
    // Nickname: NAKAM
    fallback(
        "083C52051140DB8AF770BD40C7C8883EFFF4CAF3",
        "y3afwBaM7mZ/GhTl6qR0xzZeKsvvLOAquTlOISRZPJU",
        &[
            "212.227.165.251:9001"
        ],
    ),
    // Nickname: ZXSpectrum
    fallback(
        "4B1730254163346F434DE185BBA51B62D9074FC4",
        "N9G7Y4H+9g+A8tUJ67Ox/q2r/XCRllmFQsMkbT7rwBU",
        &[
            "93.95.88.13:9001",
            "[2a02:2780::e01a]:9001"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "CDF6AECEA9A9092CA9859A78652AE60D359A44F6",
        "9rj1vQ298ChfOV3/NECgRyrNpqayOMyOwQi62+YfO2E",
        &[
            "104.244.72.168:9100",
            "[2605:6400:30:fb03:b137:4c52:b2b1:2c98]:9100"
        ],
    ),
    // Nickname: KaplanCS6
    fallback(
        "1CAFE6E87EE8BBA354DC5647C6E183D8B8AF20EC",
        "Nb1VLvmMLeNF+50JVDypLKIMqGu2Zn2uvLmSSBMle48",
        &[
            "198.73.50.66:443"
        ],
    ),
    // Nickname: ElectricSoda
    fallback(
        "60B2A557B6B9FB8CBF8168AA93FD24D8CCE815D7",
        "PQ4CO8mlYVz8XvQvdUH8PYp9h9Ql5EJn0PWwmVj0zKY",
        &[
            "209.141.38.62:443"
        ],
    ),
    // Nickname: eludemailrelay
    fallback(
        "768B488AE2C61B6FA837E3AB8DB7601E1A0B8492",
        "EvBDoxzDm2nK2qNEqjiHa4ZIYhxV93YgXZMlM6mjuBo",
        &[
            "109.236.86.109:110",
            "[2a00:7c80:0:1b0:a11:90d5:be:11e5]:110"
        ],
    ),
    // Nickname: geefMvanjetje
    fallback(
        "C804BE8FB1C7C42D43C4A5E2039E77AA0FF3A8B4",
        "HYxCWKKJMtOQIIs9UNjusSRJXj09tg7P1P78EXX+wfc",
        &[
            "192.42.116.161:9001",
            "[2001:67c:6ec:203:192:42:116:161]:9001"
        ],
    ),
    // Nickname: MaiaAlston
    fallback(
        "7EF6E998564211FB86881FEA2627AA9119BD9842",
        "F0oaccmCdnlowwGZsBTs0i5flavi5uCpUSnRp+c0ECE",
        &[
            "31.13.195.248:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "BB004C7F4C5C9FAE5E001864537F89388444F572",
        "5zUv6frGpw0nlF3nln6JhEJbbqI/gJRHuqTYANijevI",
        &[
            "37.191.195.28:8443"
        ],
    ),
    // Nickname: UnredactedManning
    fallback(
        "2A0F47CE7E1C0B7DE6FF2B3AD05DB0E77A876D98",
        "L2590wgM8WqgCRUSqEyyD+ctqyl29WmfUkOP01zlpN0",
        &[
            "23.154.177.2:443"
        ],
    ),
    // Nickname: corvuscorax
    fallback(
        "FFF4E4F51077370085A339B1F81A02BF3C2F52C9",
        "zkxUGwnPKLCZyXJYejfJK7UeJPb5bsi+owaB2/At4iA",
        &[
            "51.178.26.103:443",
            "[2001:41d0:305:2100::8550]:443"
        ],
    ),
    // Nickname: sandstorm
    fallback(
        "A1A2924158198592C3E88CB0DF23C14D9FE64328",
        "tQ0nvP4t8L+4CuxmJK43Gd/ku7L6hIeo2lTkmYd1JMg",
        &[
            "51.81.56.74:443"
        ],
    ),
    // Nickname: Pleiv
    fallback(
        "288DA2F27E30BC73FC8A84367696C9DF6B4C1B90",
        "NOfU/kowmnZzNfA+Bl7L+mcO6AFnD9s/Hf/Bd8rUt5Q",
        &[
            "195.154.133.124:9001"
        ],
    ),
    // Nickname: ThereIsNoCowLvl
    fallback(
        "5F58E9417DF94A66529864FA1134635614958A44",
        "scspuntqLCsIS0KJyM7eLbV5SqCMTZo91nZm//+25bc",
        &[
            "176.9.118.73:9993"
        ],
    ),
    // Nickname: Nightosphere
    fallback(
        "23605ADE16298CA152CC62F0C7593B3EB57BD0F4",
        "QOaHRfl4rlrXXz4/Gj8MqfGlg9dmTlPJqLnsVU3Cbdw",
        &[
            "79.196.30.109:9005"
        ],
    ),
    // Nickname: meatloaf229
    fallback(
        "C542D452D42DBD01A071D2DA1CE6EE15AF40F5C2",
        "KSx/Y6V5T3BGbSNwMbLr8ZcDnHutCEQu39+bhoGKxL8",
        &[
            "24.3.110.224:443"
        ],
    ),
    // Nickname: ParckwartEfatsum
    fallback(
        "503431F94FF8FB69F10AD59DE31F3B2C3449D990",
        "4T5x8fGmHIe4yGA4p8F0Sy/KoRkaz0mbO958a19nBXs",
        &[
            "78.94.141.180:15827",
            "[2001:470:704c::3]:15827"
        ],
    ),
    // Nickname: NameIsNotHere
    fallback(
        "A6D2C788EE9468127151A732C090674AEB0C220C",
        "SKVN6VxM1XY1vigpPToujSlCHz59d/XchZIrWxDUHnQ",
        &[
            "45.129.3.215:9002",
            "[2a00:b700::8:2bb]:9001"
        ],
    ),
    // Nickname: KoenzkTorRelay1
    fallback(
        "AEB2339CC5507533E4BDF91CB53FA130A4A72DE7",
        "+A2atuk8LSkaEyHgoJOXwUimcyKGDOc1Rgy7rv+ufeU",
        &[
            "94.212.41.237:9001"
        ],
    ),
    // Nickname: artikel10buc02
    fallback(
        "072E2883854ADA0C6B0FC1497544E529D9FD8373",
        "2+x1xsLMx7mKFIXZZ/pxnDXYA/jUc4EcPe9QK4lopdI",
        &[
            "185.100.87.250:9443",
            "[2a06:1700:0:12::1]:9443"
        ],
    ),
    // Nickname: fennee
    fallback(
        "40FAE4540CF4C126B1B15C0F5E048FDBD66E2D88",
        "7SEq0ZB4rNsS5S6JRMi5PDtLHLJ+vWtt2TNPMRj+wSM",
        &[
            "50.7.178.34:443"
        ],
    ),
    // Nickname: PieroV
    fallback(
        "0AC3C86BC9CA2A50C7762EF42ABC6D37575ACFFB",
        "2CSzPC+DTN7oolyz3/FvwOdjSRwnQnSUaKOPaqw834E",
        &[
            "164.132.226.30:22",
            "[2001:41d0:401:3100::7fda]:22"
        ],
    ),
    // Nickname: Hydra1
    fallback(
        "FF7C2604EFEE8B5898FDE1145A4CA35C8E5E5607",
        "6YwyzPAxksrAwa/GwsKQjGrx1VfyvmKYtp9gy2tOFPo",
        &[
            "193.218.118.62:9001",
            "[2a0f:e586:f:f::62]:9001"
        ],
    ),
    // Nickname: INSRelay18at5443
    fallback(
        "B65EBC8D596BBCAD0AF6092C733C00872959FD68",
        "+nYaSe1WxVARbNRNWYMhItII2GUT2jpW+3salSq/Yfs",
        &[
            "140.78.100.18:5443"
        ],
    ),
    // Nickname: bias
    fallback(
        "1A10F6E2BA45CA4A5EBAA6EF759FCBF4E8AFEEA8",
        "XEPW2s53MhjEfh5jPYeuiumgKsRrgTVRd16zwE0jXw8",
        &[
            "95.217.15.17:443",
            "[2a01:4f9:c010:7066::1]:443"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "EB3DA93B6FFFA699C1F2714C9E73FA813BB8F822",
        "nKNYsmUfNlRPwmxtrAEjPGdGvcbdQiVj4w5PLZfg2YE",
        &[
            "107.189.28.100:9100",
            "[2605:6400:30:f052:2387:1aef:e178:b3d7]:9100"
        ],
    ),
    // Nickname: just1small4relay
    fallback(
        "2DACC26F1D3BA64F32EEB4185BAD696A88BA832D",
        "zlpXTtNRFaEwv3NKoZAyR/j3mZqL6M2B2qTfrhhQPvc",
        &[
            "77.21.74.43:9001"
        ],
    ),
    // Nickname: SpeedTest2
    fallback(
        "20BC2F515B5057D598CCC018705E0ECA918E0395",
        "k1cvRC7e3YY5loVWKGuT4rPmeLbi5+hrPNeFzu6yqmM",
        &[
            "185.220.103.117:443"
        ],
    ),
    // Nickname: JumpOverAlice
    fallback(
        "101EEFBFCEC4869BA96C0E6AD2B6BBE696D98477",
        "B48nb94ocQJPtZFLpc0S6HykkkEl4jvRyb7eNtQTH2c",
        &[
            "172.86.75.174:443"
        ],
    ),
    // Nickname: NervousEnergy
    fallback(
        "75FB9A4469199F251581061391214ACFDC682EF4",
        "/B/cZ7nW/68mXhEquj5Fc1xPCseGbonX+kqXp8Z2KKI",
        &[
            "51.15.249.137:9030"
        ],
    ),
    // Nickname: luigi
    fallback(
        "ECB5CA114939B51E447792259F467C7D005C0693",
        "s3OEeBKKuEqEUTIqGHU9YfuwbtudtT+g2dBbj8tB91Y",
        &[
            "96.244.79.89:9001"
        ],
    ),
    // Nickname: gina
    fallback(
        "EE3DDF00C1ADC567F333B9BA819C8F252A32933C",
        "D/rbS7kFrMNr+T7uC+6JTj3zIb+s3GX/REC3ziNwEA0",
        &[
            "213.73.96.131:443"
        ],
    ),
    // Nickname: UDEtor
    fallback(
        "8ABC4D5F6182C7E79B087D1ED9E5CF652C83E52C",
        "hvuv4fXJqsO1hOEiGz3RCLRBSVur+LVugtISgmjLuPQ",
        &[
            "132.252.186.185:443",
            "[2001:638:501:4185:250:56ff:fe85:7034]:443"
        ],
    ),
    // Nickname: thebolt
    fallback(
        "4FC02CB4A624CE730FC4BDCBF60911913C45CEBD",
        "vrbmFArbatR3POkxqCTTT566z0ZDgcX7qTnI7/JbVHA",
        &[
            "62.212.239.170:80"
        ],
    ),
    // Nickname: nati
    fallback(
        "29FFA7A881ABADCA4EEEDD16128537BB028D5153",
        "cUJrZhhcqa8E77Zm0K34hBNzUI1MahukAkxFXjJWQrg",
        &[
            "92.223.72.168:443"
        ],
    ),
    // Nickname: torproxy02
    fallback(
        "7BB70F8585DFC27E75D692970C0EEB0F22983A63",
        "iibuh5uywUapIP8+IytB9UJjopKVd73/BJf0yQvGazw",
        &[
            "51.254.136.195:443"
        ],
    ),
    // Nickname: ExwMiaTigriMesaMou
    fallback(
        "661E08534FABDBE09BA505F7A73848371C6EF732",
        "/1kyhLXYGUEt2zooOCwgGFrDZ1jAnH42a8gCSg9e1/g",
        &[
            "83.212.72.189:443",
            "[2001:648:2ffe:501:cc00:11ff:fe4b:4ba5]:443"
        ],
    ),
    // Nickname: strainerraspi2tor
    fallback(
        "8D870EED74A4305EEAC5E8CD09F2736837367B12",
        "hPX4lO7e5TK7SYP2oVzJ6Y4iQzaiJMNCekv3ADh9mCA",
        &[
            "84.113.179.53:9001"
        ],
    ),
    // Nickname: lader
    fallback(
        "CF773DE0B4F537BB80DA35643299403B7BF11AFA",
        "mbihLJ+8Pbv66GrsEW0S8yB6Iu08QnrPnoFkSxhGAsY",
        &[
            "125.212.220.60:443"
        ],
    ),
    // Nickname: piftopp
    fallback(
        "8B0D560D2867ADB8CD443ACABD054BEBF831F3D4",
        "44Z1F+AkUwy+M5RR6DleOosiNRVxyIV/ZFQ6zThZnn0",
        &[
            "192.184.145.106:9001"
        ],
    ),
    // Nickname: Hydra64
    fallback(
        "F2DCADFB285DBAD7218E0EFA0598715DBAA8C18D",
        "ra3WT/uay5Ja1WW50pPpOQK5dvpF0S32WfNBtqOx6Po",
        &[
            "104.244.72.65:9001"
        ],
    ),
    // Nickname: oscar
    fallback(
        "6565F31D9EC0C7DFFEA1920BE3BA4C73EF35B5C4",
        "woXj1GGxbEroSMry4DUABbwN84WCsxTIN1eiIU9r9IA",
        &[
            "158.69.207.216:9001",
            "[2607:5300:201:3000::dfc]:9001"
        ],
    ),
    // Nickname: TakTor01
    fallback(
        "8696DC7AC0470F6ED5C7AC48030002D7D3716FC9",
        "pw3GlZ1B51ElynnxdJ37SZknYtX022P8wtktHwyv/vA",
        &[
            "206.217.136.47:443"
        ],
    ),
    // Nickname: laruneheureuse
    fallback(
        "3BB47BFF2788B534A5BACA37879C48EEBE5E8800",
        "qs6O2Bpa4NL3OPdqPcTnyb0cmGBRvz0LXW6AD5LZ3ZM",
        &[
            "185.65.206.154:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "082A6032BD1BB3C95F8DA9F1761F56C21297B2FC",
        "D9muE8bTzLSMlJ4aHQfdM6p0MKEH13bAiPjXKY27vz8",
        &[
            "142.4.213.105:443"
        ],
    ),
    // Nickname: Bastion
    fallback(
        "E9EF002E8D2911AFAB1121EF281858484F3ECA73",
        "ZgBHGGgf/h713v7bwi1p5UTZYTW45hkP2Y+6c589s5Y",
        &[
            "37.221.67.70:9001"
        ],
    ),
    // Nickname: KonjikiNoYami
    fallback(
        "38EF2FCFE72C49C634FE082D6CAB5D8F423B4626",
        "+Yy1OisIAwzF+JZBm/0Yi/WXHDjlYC+mTuUoLiHmOFo",
        &[
            "212.47.237.127:9001"
        ],
    ),
    // Nickname: runesandrelics
    fallback(
        "46F9FB943917858F618F2648595DEACD931D4400",
        "UyE+Ng2VkmVKYMR6dBcfqcvrV0l5SeSNJ3b5ba1MtRU",
        &[
            "54.36.108.162:443"
        ],
    ),
    // Nickname: saturna
    fallback(
        "AF2E60DEEA9971F6956A46CE0B6BC94EF558240E",
        "SIjBEIBdbn96L+PSIgayKVSvCkLdOjDxFtbFYjvkWXk",
        &[
            "158.255.215.41:7654"
        ],
    ),
    // Nickname: GreetingsFromTheNet
    fallback(
        "CF4DB0E0480FEB1E8F59C3D774EB9275283D579D",
        "OjF+0qnrGWFdepI9r4g3rA1rXVgFW9EENIeLDxgbBBs",
        &[
            "157.131.206.89:443"
        ],
    ),
    // Nickname: pilatus
    fallback(
        "629DE11D15B760521E1391B2D0722698FDC103DF",
        "DW3p85nV5Pdcm1Z23N20Y3DtAWETP6b8+3d7qBXgx2c",
        &[
            "138.201.196.156:9001",
            "[2a01:4f8:172:3e5b::2]:9001"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "098F98538A21A16332E8C4B724305C2A3496A467",
        "1aGvTj+qOQIVyFCLPtqrBroZCX7GMWneDbm2lyJ3X1w",
        &[
            "45.61.185.90:9000",
            "[2605:6400:40:febd:48d8:7117:124f:cc45]:9000"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "326853AA78DA467E997E6040ADD0DCFF840E0CB5",
        "4AQL/tpwgU4UhQEzOLxUKMvlTBFrSXOuBtnCjfAwHOE",
        &[
            "194.145.150.15:443",
            "[2001:1578:200:10::c]:443"
        ],
    ),
    // Nickname: Fastnet
    fallback(
        "22BCD0DFD148209C9860C7F89907AB4DEE974A08",
        "0ic6gubToscVteuNFKBWFg+SPtbBAqHDh4671ForwrA",
        &[
            "95.216.115.85:443"
        ],
    ),
    // Nickname: tr297e2
    fallback(
        "5F6B1DF8C9FA561EC11670C455A4A9188D7F96D9",
        "6vCPwgYEO7L5JILBwbG8I3aFjJKbgtvZmV/b5XVC/EI",
        &[
            "134.249.106.21:9001"
        ],
    ),
    // Nickname: orangepeel
    fallback(
        "DF6F2B91C93270771C8EC92D243A7CB6234244A1",
        "kCa8R2rBccI5v4Gm6Ed/QFsqBxz4Kp2dBqZQY0ddxyY",
        &[
            "58.185.69.242:8443"
        ],
    ),
    // Nickname: frankovich
    fallback(
        "7737A40305131AD8B5E60CFB9126E4BBE1ED7F76",
        "BUNird69EO2G+fVfNYKu0ZRHPRItWkZMycmUzm9KIJs",
        &[
            "46.23.72.81:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "736CD23D364941A7C23DE00FD21E44D16B50F388",
        "Q7rEzwxD/u6eZA5kqN38uww8CepTVqKhwCeFPJAfu0s",
        &[
            "134.209.224.96:443"
        ],
    ),
    // Nickname: Overjump
    fallback(
        "01CB2E297A8F586DBBCF98F028A3D1A49B0AB7BA",
        "+8h7IEXQ68+uQmcNI21cUChIEU2zNm6/b39eCR74vtQ",
        &[
            "103.228.53.155:9001"
        ],
    ),
    // Nickname: Belgarath4TOR1
    fallback(
        "AB0D440FFAE565EFCE7D0278A3E87DAE5FA29578",
        "2Ltnefyf/dr5vHEnnjueaHjgGh4w+ebNLNsgLLohJZo",
        &[
            "213.65.114.38:65187"
        ],
    ),
    // Nickname: INSRelay29at8443
    fallback(
        "73F34CDC592584C0519988E443E6FDFBA72C790B",
        "aWZmhfo9VqwGCMuK8pYMyDiczjxFTNPdcTo64Cvx7DQ",
        &[
            "140.78.100.29:8443"
        ],
    ),
    // Nickname: MyTorNode
    fallback(
        "B00B6BA943600447CF72D58DB7A35B16754E43C8",
        "CorEacsFaIhs2LqgZlS/GbC7Io+9AlaEddydvsfZPto",
        &[
            "193.108.117.59:9001"
        ],
    ),
    // Nickname: teller
    fallback(
        "E46979A3053D43ADF187463A6E4856C875BC8C89",
        "av0t9RtgMAi4009lYGps9DWt4CPNQ9I+FZwv5xM+HpI",
        &[
            "69.164.221.78:443",
            "[2600:3c03::f03c:91ff:fe70:357]:443"
        ],
    ),
    // Nickname: bonjour1
    fallback(
        "D80EA21626BFAE8044E4037FE765252E157E3586",
        "P8ZRBWRop05kV7k7Tc/k9Ijtm4VplsKS+HMWNzlGTVo",
        &[
            "188.138.33.233:443"
        ],
    ),
    // Nickname: SchweinfurtsTor2
    fallback(
        "0FDC9A7D60608123CF5432F6E25C6E4BC23E7938",
        "ZLQDDDnF73XsmHiHvHTxUQ/+gv9uw2pIS1hrhMKtFOs",
        &[
            "85.214.147.9:443"
        ],
    ),
    // Nickname: SpeedTest8
    fallback(
        "9F0FEE115DF5A0E3F5A975378064D63EC21B4A19",
        "kHg9XZGQ+B+iioJ2lMaaxSgDUoffHjjW4wAM1m7GpRg",
        &[
            "185.220.103.120:443"
        ],
    ),
    // Nickname: fiedlerRelay03
    fallback(
        "C1B513BB5E15A1887B6ADCA8C010630732FC389A",
        "PT71T5XiLM+ByxuLjmN7aJVOltYlAP8mizgm7TxxmXs",
        &[
            "37.120.190.160:9001",
            "[2a03:4000:6:b39a::2]:9001"
        ],
    ),
    // Nickname: Hydra30
    fallback(
        "22C1314867920DA37001DAD1A63F1D5CABF9DB11",
        "CIMTZUN1TPjuYwPcNhojnU6yXYfsoqP9O1Yl8dDiOXE",
        &[
            "213.164.204.90:9001"
        ],
    ),
    // Nickname: mitorip
    fallback(
        "AC7CF877B281BFEF34733E142C2A6F647AC57D82",
        "DEOZT3n+jZhVvCLVwR7v0c9jmx3/KjXSm4ft064K6eQ",
        &[
            "83.53.71.25:9001"
        ],
    ),
    // Nickname: tdz
    fallback(
        "07C8367E5B7D178B899578578BFC111FB4DDF2EA",
        "zuo87dHhm/KanoEG8haAg4fW8Mh1xznvkK4xTwcTodU",
        &[
            "51.15.85.13:3158"
        ],
    ),
    // Nickname: TorRelay01
    fallback(
        "96CAA917F65BCD62CECD236F67652BFD7C69E52E",
        "muIMY5iFdhqrfZhBBawvlF0YNsyLOv0KNgKZ70U5a4s",
        &[
            "104.37.193.102:443"
        ],
    ),
    // Nickname: mortimerAtx
    fallback(
        "EC0ABA811E4EB33DAD8BC8B7037D862BF4F3AA28",
        "7Png7c/vozvHKtMeVSeUC+GbZta2TLW6FaUkoJSc9cQ",
        &[
            "136.49.38.118:443"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "0A76C0A0A721DDBC324B705ADBFC95FD806AE855",
        "3ZBllNICd1wveBFW49Zy7UEQnvb62enzwkaG3N/I4zM",
        &[
            "107.189.28.100:9000",
            "[2605:6400:30:f052:2387:1aef:e178:b3d7]:9000"
        ],
    ),
    // Nickname: torrone
    fallback(
        "2B18524260FBF9DF47CABBC22E811E76B197395E",
        "jeDOJQO56IljFUtZIwNpiiLQiR0YiJw/Phcr8CjkKXM",
        &[
            "151.32.131.255:443"
        ],
    ),
    // Nickname: ss23voyager
    fallback(
        "CB81BCFD44FC142616BB5983648BD8AF01930789",
        "65aauuRFWdTjXpbQtkVHpTDiA11Mlgk+v9JupkO3Yis",
        &[
            "114.23.164.80:9001"
        ],
    ),
    // Nickname: freedomisnotfree
    fallback(
        "AE5B9D83AD2D7B5C10604E457ACC5E2DD9A6D81E",
        "Z9BydVrXuvBygbjD7x+w84PfPXcTryVdjUnQwRt3Txo",
        &[
            "209.141.59.180:443"
        ],
    ),
    // Nickname: bituman
    fallback(
        "431702B3A68A6015F9955DD4FD0129175B43EA0F",
        "VPFyBGe88e6vb+cd+fxfE2/L3MPtWixKXkQDzp0KvJM",
        &[
            "45.132.246.38:9001",
            "[2a03:4000:48:182:74dd:c1ff:fea8:d21e]:9001"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "28FDCC237E83C4EF83376336DB960D11D49FA756",
        "TZl9z/CXhy2IdtHs93EBnTXTx/JjPBjM5UESVzd6t1M",
        &[
            "109.92.182.91:9001"
        ],
    ),
    // Nickname: Mirage
    fallback(
        "11AEE567D24CDE680AC78BCD6EBAC36C50B3CF49",
        "yDAtllDDeAhpmI6Tn0DvPPDE5V30DVhYNWe7NCUzu58",
        &[
            "172.73.184.37:443"
        ],
    ),
    // Nickname: ramstor1
    fallback(
        "AF475359500A11B48E11561CB282955DF7AA15D0",
        "osCYS+mRU1D/L+Tp3HhVaXUjpJNdi5BuSEOXQT7Di/4",
        &[
            "95.154.25.167:9001"
        ],
    ),
    // Nickname: torexit42
    fallback(
        "B2242163F681F77F93190663AC5F696ACF76C4FD",
        "1Kg1KJeRlbexN/MmX31Ey/mCGYeujZiKIU1NtHj4DR0",
        &[
            "185.31.136.244:8181",
            "[2a00:bbe0:0:221f:9eb6:54ff:fea7:1b2d]:8181"
        ],
    ),
    // Nickname: Digitalcourage4ip7b
    fallback(
        "D13692D97236C0B8E8E19EA2DD952B5C4F9010BB",
        "7W3KnshdKM/sxyCfTww7ovrDHAjsmNhzpL+/n9TNSKw",
        &[
            "185.220.102.254:993",
            "[2a0b:f4c1:2::254]:993"
        ],
    ),
    // Nickname: AnonUS00
    fallback(
        "32C6B88EEBD4F6F5AA61F15952E8D88EAD7C67BE",
        "5rk81xh1bWMbq/IbckYTYRNm4yxUUp8UFuYOiUjoqeE",
        &[
            "40.122.165.48:443"
        ],
    ),
    // Nickname: bmwanon3
    fallback(
        "D123C0F8F562804693C47D68C61786023B295E98",
        "uL8MgzMOhfE/DXNlWZu0wrWdLY67CcFBjO0SklEWUyU",
        &[
            "176.9.1.211:9001",
            "[2a01:4f8:141:31c2:5054:ff:fe00:ea09]:9001"
        ],
    ),
    // Nickname: Assange034us2
    fallback(
        "CF8CC4763298F77FF64DAF340D26D1BBF3362C5B",
        "gngQx/g7VykzIcTbhk0ER4w621dCDDLWASd+5tuNEK0",
        &[
            "162.212.158.82:9201"
        ],
    ),
    // Nickname: morgana
    fallback(
        "CE6A9A13BB16F845C531F72923AB5D72C2C91848",
        "UHE3ewc7iPVKjZUf1zCsqKektDDForDexkzWEHIC7mo",
        &[
            "146.59.45.119:443"
        ],
    ),
    // Nickname: Quetzalcoatl
    fallback(
        "46BFF98FBD77441B28A345DFCF0F11F70EB4A4B9",
        "CPVJCRuecigkWxPCJlelUhbxwpXJFgScOx7ljo9hHlc",
        &[
            "107.189.6.61:9100",
            "[2605:6400:30:f00f:1854:a31c:7871:2582]:9100"
        ],
    ),
    // Nickname: siffeurattex
    fallback(
        "A013BBF2E931A7D58A3707C84761B3F6AAAB25D5",
        "prebFeljgfu4qg3T8vVsTsQV14eZ2t3PDTgQTjw/ohE",
        &[
            "45.142.100.30:443",
            "[2a10:46c0:0:2::13]:443"
        ],
    ),
    // Nickname: pusith
    fallback(
        "0A178D302936F209AF3DA77CCC4E3C4D5DBE11E9",
        "vr/vYa18q6Ude311z4+8z6VNUbD9Jc2ESFwk/oFpTX0",
        &[
            "178.63.172.14:443"
        ],
    ),
    // Nickname: Aramis66
    fallback(
        "39A18F31B312E5CB211781090766934C1CFDAB36",
        "uGyhuDH6nasn9nH1fqBOp4+cdsUJxtWxBgAcoZ+HdSs",
        &[
            "37.221.65.169:8443",
            "[2001:678:6d4:6010::3aed:102]:8443"
        ],
    ),
    // Nickname: torr1maiti
    fallback(
        "410F0781BCA296C866822A5D03A8D11F2457E78C",
        "kWKBiR5SxMtLfmqRxv2W5ruXBqjCjErq6+VJjz3mDPs",
        &[
            "64.44.51.37:443",
            "[2602:ffc8:1:7::bad]:443"
        ],
    ),
    // Nickname: Piplup
    fallback(
        "62F65E6377F0647CE0F0EE2AAE1641EC4AA2BD3B",
        "HamLo1mdAyWQ13HfYqeupIigFhkw2EXmbsbFSVBcVaI",
        &[
            "85.239.33.8:9001"
        ],
    ),
    // Nickname: BM14
    fallback(
        "7238EAB91E1050B6C6BEDDFCFD7A2440869B114A",
        "0VIRfMb4Y4b5x2WiBLkApVG90dRhajWHvSOvmz8upCo",
        &[
            "185.239.222.253:443",
            "[2a09:2681:101:9001::14]:443"
        ],
    ),
    // Nickname: CalyxInstitute03
    fallback(
        "84D361B736A8CD1E8818D0FC186892E91AB76881",
        "mR2gLc6sr0fsNWfINR6miGRtBOfPwF4RsfVh8DsZWmo",
        &[
            "162.247.74.213:443"
        ],
    ),
    // Nickname: FreedomRelay2
    fallback(
        "F4DD04C48A6CB6DB36DF6381FFB42D5BFAD97501",
        "qux35Ru9mlMHhKdJTRPQKiWEhy75FurGhjjNkOaTmns",
        &[
            "51.81.160.187:9001"
        ],
    ),
    // Nickname: broccoli
    fallback(
        "B1045E12FA4EA0D457A74013866CB41DC0D290BF",
        "NaTTra0m6UPqbNrUANmFWWcgcEwxWlSEF2iZrmKG1qk",
        &[
            "109.70.100.16:443",
            "[2a03:e600:100::16]:443"
        ],
    ),
    // Nickname: Shebangs
    fallback(
        "A4A79E2B8294AA2572B46C5C772E149F84FAF763",
        "VMAbkcTiGmrEjANALOrsBPm6dyn840B3nrL+3kljvRQ",
        &[
            "104.152.209.130:443"
        ],
    ),
    // Nickname: byrdeman
    fallback(
        "94318CC2299A3826D81899EB23C25A2B7D6B1FFE",
        "63VuEz0Krt1aDm25CG74h5OJRbE5OI0mSvspDK7+6i4",
        &[
            "213.227.133.129:443"
        ],
    ),
    // Nickname: ExiTOR
    fallback(
        "D9C55AC5549BF4940BE0ABBBE0E34CCC8D6D06E5",
        "XktCIgw09zYw7Gfl/9JlhrILratoye94XavEJMAVo5A",
        &[
            "54.36.101.21:9001"
        ],
    ),
    // Nickname: SpongeBob
    fallback(
        "1C0D0AF3FF05CCBBA4B6ED262196A4C5A76102E6",
        "7+ww9nAnXMLkZMGYhxpxhjPS1CK+MTcVvYw6QOn+r0A",
        &[
            "104.244.76.13:443"
        ],
    ),
    // Nickname: skewed
    fallback(
        "602A20F90E20D1B9EA4DD87AE948B590C61F8A94",
        "YCLGdUHeLIBQALe7+EDbGa6g+HZerFxyxZIn0oOnR/I",
        &[
            "49.12.93.240:443"
        ],
    ),
    // Nickname: Unnamed
    fallback(
        "B7E2EBFBE4462FC908E48007517C53ED0FF752B2",
        "FUrqbRqm1u505pWjzsYWUOOXv7w2///iepczJ7bPCrc",
        &[
            "37.59.37.59:9001"
        ],
    ),
    // Nickname: INSRelay25at8443
    fallback(
        "9385FF13D9E3BAB934ABCBA61EE63E10346E3673",
        "lID453GFgX+Jj6srQJ6zvnDm4fiCkU7ZyIv6JPgBXD8",
        &[
            "140.78.100.25:8443"
        ],
    ),
    // Nickname: SpeedTest5
    fallback(
        "3C84D97D9846044338D6DC013A6F62A9291F4614",
        "8WrRRBD18Anih4aw0JuBqyhScNzWg08e0PtWRzdJ52g",
        &[
            "185.220.103.118:9000"
        ],
    ),
]
