// DO NOT EDIT MANUALLY.
// This file was automatically generated by maint/update-release-date.

//! Release date for arti-client.
//!
//! This module is automatically generated; do not edit by hand.

/// The approximate release date for this version of arti-client.
///
/// We use this release date in [`protostatus`](crate::protostatus)
/// to decide whether a consensus is new enough
/// that we should obey its recommendations.
///
/// (We do not warn or shut down based on recommendations
/// from consensuses older than our software:
/// the fact that we released _this_ version
/// indicates that a newer consensus probably permits this version.)
pub(crate) const ARTI_CLIENT_RELEASE_DATE: &str = "2026-01-13";
